# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "range2img"

  input_dims: 4
  spatial_shape:
    - 1000
    - 1000
    - 60
  scale_list:
    - 2
    - 4
    - 8
    - 16

  hiden_size: 64
  num_classes: 20
  backbone_2d: resnet34
  pretrained2d: False

###################
## Dataset options
dataset_params:
  training_size: 19132
  dataset_type: "point_image_dataset_range_mae_kitti"
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  ignore_label: 0
  label_mapping: "./config/label_mapping/semantic-kitti.yaml"

  # 2D augmentation
  bottom_crop:
    - 1024
    - 256
  laser_range:
    - 406
    - 630

  color_jitter:
    - 0
    - 0
    - 0
  flip2d: 0
  image_normalizer:
    - [0.485, 0.456, 0.406]
    - [0.229, 0.224, 0.225]
  max_volume_space:
    - 50
    - 50
    - 2
  min_volume_space:
    - -50
    - -50
    - -4
  seg_labelweights:
    - 0
    - 55437630
    - 320797
    - 541736
    - 2578735
    - 3274484
    - 552662
    - 184064
    - 78858
    - 240942562
    - 17294618
    - 170599734
    - 6369672
    - 230413074
    - 101130274
    - 476491114
    - 9833174
    - 129609852
    - 4506626
    - 1168181

  train_data_loader:
    # data_path: "/media/yanqiao/Seagate Hub/semantic-kitti/dataset/sequences/"
    data_path: "/home/yanqiao/Documents/semantic-kitti/dataset/sequences/"
    batch_size: 2
    shuffle: True
    num_workers: 8
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False

  val_data_loader:
    # data_path: "/media/yanqiao/Seagate Hub/semantic-kitti/dataset/sequences/"
    data_path: "/home/yanqiao/Documents/semantic-kitti/dataset/sequences/"
    shuffle: False
    num_workers: 8

    # normal test
    batch_size: 16
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False


###################
## Train params
train_params:
  max_num_epochs: 50
  learning_rate: 1.5e-4
  optimizer: Adam  # [SGD, Adam]
  lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 0.05

  lambda_seg2d: 1
  lambda_xm: 0.05
